name: backup to gitlab
on: [push]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
#  backup-to-gitlabwh:
#    uses: linuxdeepin/.github/.github/workflows/backup-to-gitlabwh.yml@master
#    secrets: inherit

  backup-to-gitee:
    uses: linuxdeepin/.github/.github/workflows/backup-to-gitee.yml@master
    secrets: inherit

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Anolis
        run: |
          git clone --bare https://github.com/linuxdeepin/youqu.git .git
          git remote set-url origin https://myml:${{ secrets.GITEE_SYNC_TOKEN }}@gitee.com/anolis/youqu.git
          git push -f --all --prune origin
          git push --tags origin
