name: backup to gitlab
on: [push]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  backup-to-gitlabwh:
    uses: linuxdeepin/.github/.github/workflows/backup-to-gitlabwh.yml@youqu3
    secrets: inherit

  backup-to-gitee:
    uses: linuxdeepin/.github/.github/workflows/backup-to-gitee.yml@youqu3
    secrets: inherit
