name: backup to gitlab
on: [push]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
#  backup-to-gitlabwh:
#    uses: linuxdeepin/.github/.github/workflows/backup-to-gitlabwh.yml@master
#    secrets: inherit

  backup-to-gitee:
    uses: linuxdeepin/.github/.github/workflows/backup-to-gitee.yml@master
    secrets: inherit

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Anolis
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:linuxdeepin/youqu.git
          destination-repo: git@gitee.com:anolis/youqu.git
